/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Archive: typeof import('./src/components/workSpace/Archive.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BoardCard: typeof import('./src/components/workSpace/BoardCard.vue')['default']
    BoardListsExample: typeof import('./src/components/BoardListsExample.vue')['default']
    CardComments: typeof import('./src/components/cardProperties/CardComments.vue')['default']
    CardDateRange: typeof import('./src/components/cardProperties/CardDateRange.vue')['default']
    CardDescription: typeof import('./src/components/cardProperties/CardDescription.vue')['default']
    CardImportance: typeof import('./src/components/cardProperties/CardImportance.vue')['default']
    CardMembers: typeof import('./src/components/cardProperties/CardMembers.vue')['default']
    CardModal: typeof import('./src/components/CardModal.vue')['default']
    CardNotifications: typeof import('./src/components/cardProperties/CardNotifications.vue')['default']
    CardTags: typeof import('./src/components/cardProperties/CardTags.vue')['default']
    CardToDoList: typeof import('./src/components/cardProperties/CardToDoList.vue')['default']
    CardWorkingHours: typeof import('./src/components/cardProperties/CardWorkingHours.vue')['default']
    FilterMenu: typeof import('./src/components/workSpace/FilterMenu.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconSpin: typeof import('./src/components/IconSpin.vue')['default']
    List: typeof import('./src/components/Board/list.vue')['default']
    MemberList: typeof import('./src/components/Board/member-list.vue')['default']
    NewBoardModal: typeof import('./src/components/workSpace/NewBoardModal.vue')['default']
    NoData: typeof import('./src/components/workSpace/NoData.vue')['default']
    PersonalModal: typeof import('./src/components/PersonalModal.vue')['default']
    Pinned: typeof import('./src/components/workSpace/Pinned.vue')['default']
    QuillEditor: typeof import('./src/components/QuillEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    ShareModal: typeof import('./src/components/workSpace/ShareModal.vue')['default']
    WorkSpace: typeof import('./src/components/workSpace/WorkSpace.vue')['default']
  }
}
